version: '3.7'

services:

  mysql:
    container_name: mysqlcalender
    build:
      context: ./mysql
      dockerfile: Dockerfile
    expose:
      - 3306
    ports:
      - 5510:3306
    volumes:
      - mysql-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=1234

volumes:
  mysql-data:
